Algoritmo "Classificação por idade"

Var

n1: inteiro

Inicio

escreva ("Qual a idade? ")
leia(n1)
se n1 <= 12 entao
   escreva("Classe: Criança")
senao
     se n1 <= 17 entao
        escreva("Classe: Adolescente")
senao
     se n1 <= 59 entao
        escreva("Classe: Adulto")
senao
     se n1 >= 60 entao
        escreva("Classe: Idoso")
     fimse
fimse
fimse
fimse
Fimalgoritmo