Algoritmo "MédiaVariosValores"

var

n1: real
n2: real
n3: real
n4: real
n5: real
m: real

inicio

escreva ("Qual a primeira nota? ")
leia(n1)
escreva ("Qual a segunda nota? ")
leia(n2)
escreva ("Qual a terceira nota? ")
leia(n3)
escreva ("Qual a quarta nota? ")
leia(n4)
escreva ("Qual a quinta nota? ")
leia(n5)
m <- (n1 + n2 + n3 + n4 + n5)/5
escreva ("A média é: ",m)

fimalgoritmo